Feat/ch_board_editor
APP-iOS5th/FinalProject-Letports pull request #17
Opened 2024-08-18 14:03 UTC by iOS-Ruel

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역
기능적인 부분(게시물 업로드, 사진 업로드)은 추후 진행 예정

### 추가 구현 사항

1. 제목, 내용 작성시 작성 버튼 enabled 처리
2. 사진 추가
3. Compostional Layout 적용

- [x] 작업 내역 작성

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] PR과 관련없는 변경사항이 없는가?
- [x] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 리스트 내 사진을 추가해아하기 때문에 TableView - TableViewCell 안에 CollectionView를 넣을 생각이었지만
데이터를 전달해야하는 과정이 불필요하게 추가 Depth가 필요하기 때문에 CollectionView만으로 Compositional Layout을 적용하였음.
해당 부분에 대해서 다양한 방법이 있지만 Compositional Layout이 적합하다고 판단함.

- TextView, TextField 글자수 관련하여 한글입력시 이슈가 있어 구현한 코드 라이브러리화 시켰음.
- https://github.com/iOS-Ruel/KoTextCountLimit 에서 확인가능 ( 현재 SPM으로 라이브러리 추가해두었음 )
```swift
글자수 제한이 필요하게 되어 이전에 개인적으로 구현해 놓았던 코드를 사용했음
그런데 UITextField, UITextView에서 Text를 Count로만 체크하는 경우

Ex) 10글자 제한일경우
if text.count >= 10 {
    return false
}

"안녕하세요안녕하세요" 까지 작성한 경우
백스페이스, 즉 글자를 지우는게 동작하지 않음.
이미 10글자라고 판단하였기 때문에 false를 Return 하고 있기 때문

키보드에서 입력된 글자를 cstring으로 변환하고
입력된 키가 백스페이스 키인지 확인
따라서 글자수를 체크하기 이전에 백스페이스 키가 입력되었는지를 확인

한글의 특성상 초성, 중성, 종성이 있는데
중성일 경우 다음으로 입력되는 글자가 자음, 모음인지 확인
모음은 허용하지 않고 자음만 허용 처리 (받침이기 때문에)
자음까지 입력 되어도(받침까지 입력되어도) 백스페이스 키는 사용 가능하도록 처리
--------
즉 한글은 중성까지 입력되면 해당하는 글자수 까지의 count를 체크하기 때문에  종성을 입력 할 수 없는 상황이 있었음
이를 해결하기 위한 코드임.
```
![초성, 중성, 종성](https://github.com/user-attachments/assets/cebf6cad-dbf9-47b4-b5b2-e4b19a4991b0)

<br/><br/>

2024-08-18 17:03 UTC, realdevyun requested changes
파일 중복이 있어서 리젝할게요

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/BoarderEditorVC.swift
> +    private func presentImagePC() {
presentImagePC <<< 줄임말 어려워요ㅠㅠ

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/BoarderEditorVC.swift
> +        let cnv = CustomNavigationView(isLargeNavi: .small,
cnv <<< 줄임말이 어렵네요ㅠ

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/BoarderEditorVC.swift
> +    private func showAccessDeniedAlert() {
이 부분에 대해서 앱 사용성 측면에서 어떻게 처리할지 고민해봐야 할듯싶어요.

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/Cell/BoardEditorContentCVCell.swift
> +    func textViewDidChange(_ textView: UITextView) {
뭔가 함수명이 살짝 혼동이 오는거 같습니다.
textViewDidChange -> textCountViewDidChange 같이 글자수 라는 것을 조금 더 명확하게 명시하면 좋을꺼같아요.

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/Cell/BoardEditorTitleCVCell.swift
> +        return koTextLimit.shouldChangeText(for: textField, in: range, replacementText: string, maxCharacterLimit: 10)
글자수 제한 관련 정해야될듯요!

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/Cell/BoarderEditorPhotoCVCell.swift
BoardEditorPhotoCVCell.swift 파일이랑 중복인듯 싶습니당

2024-08-18 17:03 UTC, allealleios commented on Letports/Letports/BoaderEditor/Cell/BoardEditorPhotoCVCell.swift
BoarderEditorPhotoCVCell.swift 파일이랑 중복인듯 싶습니당

2024-08-18 17:03 UTC, realdevyun commented on Letports/Letports/Extension/Extension+UICollectionView.swift
이런 익스텐션 좋습니다~~~
너무 편리해요!

2024-08-18 17:03 UTC, realdevyun commented on Letports/Letports/Extension/Extension+UITableView.swift
어케찾았누..ㄷㄷ

2024-08-18 17:29 UTC, iOS-Ruel commented on Letports/Letports/BoaderEditor/Cell/BoardEditorPhotoCVCell.swift
- 수정완료

2024-08-18 17:31 UTC, realdevyun approved these changes
중복 파일 삭제된거 확인완료

2024-08-19 00:27 UTC, mo-si-dev approved these changes
확인완료

2024-08-19 00:36 UTC, merged