Feat/sh gathering detail UI
APP-iOS5th/FinalProject-Letports pull request #21
Opened 2024-08-21 05:12 UTC by yachae96

### 📕 Issue Number

Close #

### 📙 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] 소모임상세페이지 UI구현
- [x] 게시글상세UI구현

### 📘 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### 📋 체크리스트

- [x ] Merge 하는 브랜치가 올바른가?
- [ ] 코딩컨벤션을 준수하는가?
- [ ] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?
- [ ] 변경사항이 효과적이거나 동작이 작동한다는 것을 보증하는 테스트를 추가하였는가?
- [ ] 새로운 테스트와 기존의 테스트가 변경사항에 대해 만족하는가?

### 📝 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 뷰만그려져있고 데이터는 하드코딩되어있음

- vm에서 데이터구조체 수정예정

<br/><br/>

2024-08-21 08:43 UTC, iOS-Ruel approved these changes
급하게보느라 수정이 필요한부분을 다 체크못했는데
확인부탁드려요

그리고 데이터 연동하면서 또는 그 이후에 전체적으로 리팩토링이 필요할거 같아요.

2024-08-21 08:43 UTC, iOS-Ruel commented on Letports/Letports/BoardViewController.swift
> +        self.view.backgroundColor = .lp_background_white
메서드화 시키는건 어떨까 싶음요
self.view.backgroundColor 는 왜 두개일까요

```Swift
func setupUI() { 
self.view.backgroundColor = .white
        navigationView.delegate = self
        self.view.addSubview(navigationView)
        NSLayoutConstraint.activate([
            navigationView.topAnchor.constraint(equalTo: self.view.safeAreaLayoutGuide.topAnchor),
            navigationView.leadingAnchor.constraint(equalTo: self.view.leadingAnchor),
            navigationView.trailingAnchor.constraint(equalTo: self.view.trailingAnchor)
        ])

        self.view.backgroundColor = UIColor("#BBBBBB", alpha: 1.0)
        self.view.backgroundColor = .lp_background_white
}
````

2024-08-21 08:43 UTC, iOS-Ruel commented on Letports/Letports/Gathering/GatheringBoardDetail/Cell/GatheringBoardCommentTVCell.swift
> +}
TableViewCell안에 TableView 넣지말고
이전 TableView에서 모든걸 Cell로도 처리할 수 있을거 같아요

2024-08-21 08:43 UTC, iOS-Ruel commented on Letports/Letports/Gathering/GatheringDetail/Cell/GatheringDetailBoardTVCell.swift
> +	}
정렬 불편

2024-08-21 08:43 UTC, iOS-Ruel commented on Letports/Letports/Gathering/GatheringDetail/Cell/GatheringDetailProfileCVCell.swift
> +	private let userImageBt: UIButton = {
Bt -> Btn으로 하던지 Button으로 하던지 통일 필요할듯
Bt만 봤을때 버튼이라고 인식이 안됌

2024-08-21 12:07 UTC, yachae96 commented on Letports/Letports/BoardViewController.swift
> +        self.view.backgroundColor = .lp_background_white
확인했습니다

2024-08-21 12:07 UTC, yachae96 commented on Letports/Letports/Gathering/GatheringDetail/Cell/GatheringDetailBoardTVCell.swift
> +	}
정렬해놓을게요

2024-08-21 12:09 UTC, yachae96 commented on Letports/Letports/Gathering/GatheringBoardDetail/Cell/GatheringBoardCommentTVCell.swift
> +}
성근님하고 얘기를 나눠봤는데 수정하는데 시간걸릴꺼같아서 일단 그대로 두고 나중에 리펙토링해보도록 할게요

2024-08-21 12:09 UTC, yachae96 commented on Letports/Letports/Gathering/GatheringDetail/Cell/GatheringDetailProfileCVCell.swift
> +	private let userImageBt: UIButton = {
btn으로 통일해놓을게요

2024-08-21 14:19 UTC, allealleios commented on Letports/Letports/BoardViewController.swift
> +        self.view.backgroundColor = .lp_background_white
> 저 파일은 종찬님이 만드신 파일같은데요? backgroundColor가 왜 2개인지는 잘 모르겠습니다.

제가 만든거 아닙니다😅

2024-08-22 08:56 UTC, allealleios requested changes

2024-08-22 08:56 UTC, allealleios commented on Letports/Letports/BoardViewController.swift
이거 밑에 Letports/Letports/ViewController.swift 파일이랑 중복같은데 확인 부탁드려요

2024-08-22 08:56 UTC, allealleios commented on Letports/Letports/ViewController.swift
이거 위에 Letports/Letports/BoardViewController.swift 파일이랑 중복같은데 확인 부탁드려요

2024-08-22 13:50 UTC, allealleios approved these changes
중복파일 삭제 확인완료

2024-08-22 14:35 UTC, merged